[project]
name = "mbctl"
version = "0.2.0"
description = "Container tools for nspawn management"
authors = [
    { name = "Neboer", email = "rubinposter@gmail.com" }
]
dependencies = []

[project.scripts]
mbctl = "mbctl.main:main"